AWStemplateFormatVersion: '2010-09-09'
Description: Mi Primer Lambda con CloudFormation

Parameters:
  NombreLambda:
    Description: Nombre de la función Lambda
    Type: String

  RuntimeLamda:
    Description: Ingresa el runtime de la función Lambda
    Type: String
    Default: python3.7
    AllowedValues:
      - python3.7
      - python2.7
      - ruby2.5
      - nodejs8.10
      - java8
      - dotnetcore2.1

Resources:
  LambdaFindVoto:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref NombreLambda
      Handler: lambda_funcion.lambda_handler
      Runtime: !Ref RuntimeLamda
      MemorySize: 512
      Timeout: 600
      Role: !GetAtt LambdaRoleApp.Arn

Outputs:
  LambdaARN:
    Description: "ARN de ña función Lambda"
    Value:
      !GetAtt LambdaRoleApp.Arn
    Export:
      Name: LambdaFindVotoArn
  LambdaName:
    Description: "Nombre de la Función Lambda"
    Value:
      !Ref LambdaFindVoto
    Export:
      Name: LambdaFindVotoName